/**
 * IPC Channel Constants
 * 
 * Single Source of Truth for all Electron IPC communication.
 */

export const IPC_CHANNELS = {
  APP: {
    GET_VERSION: 'app:getVersion',
  },
  DATABASE: {
    GET_SETTING: 'db:getSetting',
    SET_SETTING: 'db:setSetting',
    GET_ALL_SETTINGS: 'db:getAllSettings',
    GET_DASHBOARD_SUMMARY: 'db:getDashboardSummary',
    MEDIA_LIST: 'db:media:list',
    MEDIA_COUNT: 'db:media:count',
    MEDIA_GET_ITEM: 'db:media:getItem',
    MEDIA_GET_BY_ID: 'db:getMediaItemById',
    MEDIA_UPSERT: 'db:upsertMediaItem',
    MEDIA_GET_VERSIONS: 'db:getMediaItemVersions',
    MEDIA_DELETE: 'db:deleteMediaItem',
    TV_EPISODES_COUNT: 'db:countTVEpisodes',
    TVSHOWS_LIST: 'db:tvshows:list',
    TVSHOWS_COUNT: 'db:tvshows:count',
    GET_LETTER_OFFSET: 'db:getLetterOffset',
    GET_QUALITY_SCORES: 'db:getQualityScores',
    GET_QUALITY_SCORE_BY_MEDIA_ID: 'db:getQualityScoreByMediaId',
    UPSERT_QUALITY_SCORE: 'db:upsertQualityScore',
    SET_LIBRARY_PROTECTED: 'db:setLibraryProtected',
    VERIFY_PIN: 'db:verifyPin',
    SET_PIN: 'db:setPin',
    HAS_PIN: 'db:hasPin',
    GET_LIBRARY_STATS: 'db:getLibraryStats',
    GET_LIBRARY_OVERVIEW: 'db:getLibraryOverview',
    GET_PATH: 'db:getPath',
    OPEN_FOLDER: 'db:openFolder',
    EXPORT: 'db:export',
    EXPORT_CSV: 'db:exportCSV',
    IMPORT: 'db:import',
    RESET: 'db:reset',
    ADD_EXCLUSION: 'db:addExclusion',
    REMOVE_EXCLUSION: 'db:removeExclusion',
    GET_EXCLUSIONS: 'db:getExclusions',
    BATCH_ADD_EXCLUSIONS: 'db:batchAddExclusions',
  },
  SOURCES: {
    LIST: 'sources:list',
    ADD: 'sources:add',
    REMOVE: 'sources:remove',
    TOGGLE: 'sources:toggle',
    TEST_CONNECTION: 'sources:testConnection',
    GET_STATS: 'sources:getStats',
    GET_SUPPORTED_PROVIDERS: 'sources:getSupportedProviders',
    GET_LIBRARIES_WITH_STATUS: 'sources:getLibrariesWithStatus',
    SET_LIBRARIES_ENABLED: 'sources:setLibrariesEnabled',
    OPEN_FOLDER: 'sources:openFolder',
    PLEX: {
      START_AUTH: 'plex:startAuth',
      CHECK_AUTH: 'plex:completeAuth',
      AUTHENTICATE_AND_DISCOVER: 'plex:authenticateAndDiscover',
      SELECT_SERVER: 'plex:selectServer',
      GET_SERVERS: 'plex:getServers',
    },
    JELLYFIN: {
      AUTHENTICATE: 'jellyfin:authenticateCredentials',
      GET_LIBRARIES: 'jellyfin:getLibraries',
    }
  },
  TASK_QUEUE: {
    GET_STATE: 'taskQueue:getState',
    PAUSE: 'taskQueue:pause',
    RESUME: 'taskQueue:resume',
    CANCEL_TASK: 'taskQueue:cancelTask',
    CLEAR_HISTORY: 'taskQueue:clearHistory',
    ADD_TASK: 'taskQueue:addTask',
    ADD_TASKS: 'taskQueue:addTasks',
  },
  WISHLIST: {
    GET_ALL: 'wishlist:getAll',
    GET_COUNT: 'wishlist:getCount',
    GET_COUNTS_BY_REASON: 'wishlist:getCountsByReason',
    GET_REGION: 'wishlist:getRegion',
    SET_REGION: 'wishlist:setRegion',
    ADD: 'wishlist:add',
    ADD_BULK: 'wishlist:addBulk',
    UPDATE: 'wishlist:update',
    REMOVE: 'wishlist:remove',
    CHECK_EXISTS: 'wishlist:checkExists',
    GET_STORE_LINKS: 'wishlist:getStoreLinks',
    OPEN_STORE_LINK: 'wishlist:openStoreLink',
    EXPORT_CSV: 'wishlist:exportCsv',
  },
  LOGGING: {
    GET_ALL: 'logs:getAll',
    CLEAR: 'logs:clear',
    EXPORT: 'logs:export',
    SET_VERBOSE: 'logs:setVerbose',
    IS_VERBOSE: 'logs:isVerbose',
    GET_FILE_SETTINGS: 'logs:getFileLoggingSettings',
    SET_FILE_SETTINGS: 'logs:setFileLoggingSettings',
    OPEN_LOG_FOLDER: 'logs:openLogFolder',
    INFO: 'logs:info',
    WARN: 'logs:warn',
    ERROR: 'logs:error',
    DEBUG: 'logs:debug',
  },
  MONITORING: {
    GET_CONFIG: 'monitoring:getConfig',
    SET_CONFIG: 'monitoring:setConfig',
    START: 'monitoring:start',
    STOP: 'monitoring:stop',
    IS_ACTIVE: 'monitoring:isActive',
    GET_STATUS: 'monitoring:getStatus',
    GET_HISTORY: 'monitoring:getHistory',
    CLEAR_HISTORY: 'monitoring:clearHistory',
    FORCE_CHECK: 'monitoring:forceCheck',
  },
  NOTIFICATIONS: {
    GET_ALL: 'notifications:getAll',
    MARK_READ: 'notifications:markRead',
    MARK_ALL_READ: 'notifications:markAllRead',
    CLEAR_ALL: 'notifications:clearAll',
  },
  AUTO_UPDATE: {
    GET_STATE: 'autoUpdate:getState',
    CHECK_FOR_UPDATES: 'autoUpdate:checkForUpdates',
    DOWNLOAD_UPDATE: 'autoUpdate:downloadUpdate',
    INSTALL_UPDATE: 'autoUpdate:installUpdate',
  },
  COLLECTIONS: {
    ANALYZE_ALL: 'collections:analyzeAll',
    CANCEL_ANALYSIS: 'collections:cancelAnalysis',
    GET_ALL: 'collections:getAll',
    GET_INCOMPLETE: 'collections:getIncomplete',
    GET_STATS: 'collections:getStats',
    DELETE: 'collections:delete',
  },
  DUPLICATES: {
    GET_PENDING: 'duplicates:getPending',
    SCAN: 'duplicates:scan',
    GET_RECOMMENDATION: 'duplicates:getRecommendation',
    RESOLVE: 'duplicates:resolve',
  },
  AI: {
    IS_CONFIGURED: 'ai:isConfigured',
    GET_RATE_LIMIT_INFO: 'ai:getRateLimitInfo',
    TEST_API_KEY: 'ai:testApiKey',
    SEND_MESSAGE: 'ai:sendMessage',
    STREAM_MESSAGE: 'ai:streamMessage',
    CHAT_MESSAGE: 'ai:chatMessage',
    QUALITY_REPORT: 'ai:qualityReport',
    UPGRADE_PRIORITIES: 'ai:upgradePriorities',
    COMPLETENESS_INSIGHTS: 'ai:completenessInsights',
    WISHLIST_ADVICE: 'ai:wishlistAdvice',
    COMPRESSION_ADVICE: 'ai:compressionAdvice',
    EXPLAIN_QUALITY: 'ai:explainQuality',
  },
  JELLYFIN: {
    IS_QUICK_CONNECT_ENABLED: 'jellyfin:isQuickConnectEnabled',
    INITIATE_QUICK_CONNECT: 'jellyfin:initiateQuickConnect',
    CHECK_QUICK_CONNECT_STATUS: 'jellyfin:checkQuickConnectStatus',
    COMPLETE_QUICK_CONNECT: 'jellyfin:completeQuickConnect',
    AUTHENTICATE_CREDENTIALS: 'jellyfin:authenticateCredentials',
  },
  MUSIC: {
    SCAN_LIBRARY: 'music:scanLibrary',
    GET_ARTIST_BY_ID: 'music:getArtistById',
    GET_ALBUM_BY_ID: 'music:getAlbumById',
    GET_TRACKS_BY_ALBUM: 'music:getTracksByAlbum',
    GET_STATS: 'music:getStats',
    GET_ALBUM_QUALITY: 'music:getAlbumQuality',
    GET_ALBUMS_NEEDING_UPGRADE: 'music:getAlbumsNeedingUpgrade',
    ANALYZE_ALL_QUALITY: 'music:analyzeAllQuality',
    ANALYZE_ALL: 'music:analyzeAll',
    CANCEL_ANALYSIS: 'music:cancelAnalysis',
    SEARCH_MB_ARTIST: 'music:searchMusicBrainzArtist',
    ANALYZE_ARTIST_COMPLETENESS: 'music:analyzeArtistCompleteness',
    GET_ARTIST_COMPLETENESS: 'music:getArtistCompleteness',
    GET_ALL_ARTIST_COMPLETENESS: 'music:getAllArtistCompleteness',
    ANALYZE_ALBUM_TRACK_COMPLETENESS: 'music:analyzeAlbumTrackCompleteness',
    GET_ALBUM_COMPLETENESS: 'music:getAlbumCompleteness',
    GET_ALL_ALBUM_COMPLETENESS: 'music:getAllAlbumCompleteness',
    GET_INCOMPLETE_ALBUMS: 'music:getIncompleteAlbums',
    CANCEL_SCAN: 'music:cancelScan',
    FIX_ARTIST_MATCH: 'music:fixArtistMatch',
    SEARCH_MB_RELEASE: 'music:searchMusicBrainzRelease',
  },
  SETTINGS: {
    GET_NFS_MAPPINGS: 'settings:getNfsMappings',
    SET_NFS_MAPPINGS: 'settings:setNfsMappings',
    TEST_NFS_MAPPING: 'settings:testNfsMapping',
  },
  MOVIE: {
    SEARCH_TMDB: 'movie:searchTMDB',
    FIX_MATCH: 'movie:fixMatch',
  },
  MEDIA: {
    SEARCH: 'media:search',
  }
} as const
