import { describe, expect, it, vi } from 'vitest'
import { PlaybackCompatibilityService, type PlaybackDecisionProvider } from '@main/services/PlaybackCompatibilityService'
import type { PlaybackTargetProfile } from '@main/types/playbackTarget'

const profile: PlaybackTargetProfile = { id: 'p', name: 'P', isBuiltin: false, createdAt: '', updatedAt: '', definition: { containers: ['matroska'], video: { codecs: ['hevc'], profiles: ['Main 10'], levels: [51], maxWidth: 3840, maxHeight: 2160, maxFrameRate: 60, bitDepths: [10] }, hdr: { formats: ['HDR10'], fallbackRequired: false }, audio: { codecs: ['eac3'], maxChannels: 8, objectAudio: false, outputPath: 'device' }, subtitles: { formats: ['srt'], embedded: true, external: true, burnIn: false }, network: { sustainableBitrate: 100000000 }, providers: { plex: { clientProduct: 'Plex', clientPlatform: 'webOS', clientVersion: '4' } } } }
const analysis = { success: true, filePath: 'x', container: 'matroska', overallBitrate: 1, video: { index: 0, codec: 'hevc', profile: 'Main 10', level: 51, width: 1920, height: 1080, frameRate: 24, bitDepth: 10, hdrFormat: 'HDR10' as const }, audioTracks: [{ index: 1, codec: 'eac3', channels: 2, hasObjectAudio: false, isDefault: true }], subtitleTracks: [] }
function db(sourceType = 'local') { return { media: { getItemById: vi.fn().mockResolvedValue({ file_path: 'x', source_type: sourceType, source_id: 'source-1', plex_id: '42' }) }, playbackTargetProfiles: { get: vi.fn().mockResolvedValue(profile) } } as never }
describe('PlaybackCompatibilityService', () => {
  it('returns generic assessment for non-Plex sources', async () => { const result = await new PlaybackCompatibilityService(db(), { analyzeFile: vi.fn().mockResolvedValue(analysis) } as never).analyze(1, 'p'); expect(result.presentation).toBe('compatible'); expect(result.providerDecision).toBeUndefined() })
  it('reports provider unavailability explicitly', async () => { const provider: PlaybackDecisionProvider = { getDecision: vi.fn().mockRejectedValue(new Error('offline')) }; const result = await new PlaybackCompatibilityService(db('plex'), { analyzeFile: vi.fn().mockResolvedValue(analysis) } as never, { plex: provider }).analyze(1, 'p'); expect(result.presentation).toBe('provider-decision-unavailable'); expect(result.providerDecisionError).toBe('offline') })
})
